# name: Python Lint

# on:
#   push:
#     branches: [main]

# jobs:
#   validate:
#     runs-on: ubuntu-24.04
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

#     steps:
#       - name: Checkout code of repo
#         uses: actions/checkout@v4


#       # Python all versions
#       - name: Setup python ${{ matrix.python-version}}
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Verify Python 3.12
#         run: python --version

#       - name: Install dependencies (3.12)
#         run: |    # | means multi-line command block
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run linter (3.12)
#         run: flake8 app.py
