# API keys, sensitive data, credentials
# we use Gitleaks for this

name: Secrets scan

on:
  workflow_call:


jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Run GitLeaks Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #github actions will create and manages the secret
